[package]
name = "my_clipboard_playlist"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
eframe = { version = "0.36.2", features = ["persistence"] }
egui_extras = { version = "0.36.2", features = ["file", "http", "image", "webp"] }
ehttp = { version = "0.7.1", default-features = false }
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "webp"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
url = "2.5.8"
